(() => {
"use strict";
const cfg=Object.assign({endpoint:"https://freezzgames-live-monitor.onrender.com/api/live",pollMs:300000},window.FZG_LIVE_CONFIG||{});
const S={all:[],online:[],selectedId:null,muted:true,loading:false};
const $=id=>document.getElementById(id);
const h=()=>window.FZG?.platform?.haptic?.("light");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function score(x){return Number(x?.qualityScore||0)*.42+Number(x?.trafficScore||0)*.28+Number(x?.stabilityScore||0)*.22+Number(x?.latencyScore||0)*.08}
function source(s){return [...(s.sources||[])].filter(x=>x.live&&x.embedUrl).sort((a,b)=>score(b)-score(a))[0]||null}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalize(p){const a=Array.isArray(p)?p:(Array.isArray(p?.streamers)?p.streamers:[]);return a.map(x=>{x={id:String(x.id||""),name:String(x.name||"Стример"),avatar:String(x.avatar||"🎮"),game:String(x.game||""),category:String(x.category||""),live:!!x.live,liveStartedAt:x.liveStartedAt||null,lastStreamAt:x.lastStreamAt||null,lastStreamTitle:String(x.lastStreamTitle||""),sources:Array.isArray(x.sources)?x.sources:[]};x.selectedSource=source(x);return x}).filter(x=>x.id)}
function fmt(v){try{return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}catch{return String(v)}}
function empty(){const m=$("liveMain");if(m)m.innerHTML='<div class="live-empty"><div class="live-empty-icon">📡</div><div class="live-empty-title">СЕЙЧАС НЕТ ТРАНСЛЯЦИЙ</div><div class="live-empty-text">Здесь автоматически появится подтверждённый LIVE-эфир.</div></div>';if($("liveCarousel"))$("liveCarousel").innerHTML=""}
function main(s){const m=$("liveMain");if(!m)return;if(!s||!s.live||!s.selectedSource){empty();return}const u=esc(s.selectedSource.embedUrl);m.innerHTML='<div class="live-video-frame"><iframe class="live-video" src="'+u+'" title="'+esc(s.name)+' — LIVE" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen loading="eager"></iframe><div class="live-video-shade"><div class="live-streamer-badge"><span class="live-dot"></span> LIVE</div><button class="live-sound-btn" id="liveSoundBtn" type="button">🔇</button></div><div class="live-streamer-info"><div class="live-streamer-avatar">'+esc(s.avatar)+'</div><div class="live-streamer-copy"><strong>'+esc(s.name)+'</strong><span>'+esc(s.game||s.category||"LIVE")+'</span></div></div></div>';
$("liveSoundBtn")?.addEventListener("click",()=>{S.muted=!S.muted;$("liveSoundBtn").textContent=S.muted?"🔇":"🔊";h();window.FZG?.live?.onSoundChange?.(S.muted,s,s.selectedSource)});}
function carousel(){const host=$("liveCarousel");if(!host)return;const a=shuffle(S.online.filter(x=>x.id!==S.selectedId)).slice(0,8);host.innerHTML=a.map(x=>'<button class="live-carousel-card" type="button" data-live-id="'+esc(x.id)+'"><div class="live-carousel-thumb"><span class="live-dot"></span><span class="live-thumb-avatar">'+esc(x.avatar)+'</span></div><div class="live-carousel-name">'+esc(x.name)+'</div><div class="live-carousel-game">'+esc(x.game||x.category||"LIVE")+'</div></button>').join("");host.querySelectorAll("[data-live-id]").forEach(b=>b.addEventListener("click",()=>select(b.dataset.liveId,true)))}
function list(){const host=$("liveStreamerList");if(!host)return;const on=S.all.filter(x=>x.live&&x.selectedSource),off=S.all.filter(x=>!x.live||!x.selectedSource);const row=(x,isOn)=>'<button class="live-list-row" type="button" data-live-list-id="'+esc(x.id)+'"><span class="live-list-avatar">'+esc(x.avatar)+'</span><span class="live-list-main"><strong>'+esc(x.name)+'</strong><small>'+esc(x.game||x.category||"Стример")+'</small><em>'+(isOn?"СЕЙЧАС В ЭФИРЕ":(x.lastStreamAt?"Последний эфир: "+fmt(x.lastStreamAt):"Последний эфир неизвестен"))+'</em></span><span class="live-list-status '+(isOn?"online":"offline")+'">'+(isOn?"LIVE":"OFF")+'</span></button>';host.innerHTML='<div class="live-list-section-title">🔴 ONLINE · '+on.length+'</div>'+(on.map(x=>row(x,true)).join("")||'<div class="live-list-none">Сейчас никто не в эфире.</div>')+'<div class="live-list-section-title offline-title">⚫ OFFLINE · '+off.length+'</div>'+(off.map(x=>row(x,false)).join("")||'<div class="live-list-none">Нет офлайн-профилей.</div>');host.querySelectorAll("[data-live-list-id]").forEach(b=>b.addEventListener("click",()=>{const x=S.all.find(v=>v.id===b.dataset.liveListId);if(!x)return;closeList();if(x.live&&x.selectedSource)select(x.id,true);else offline(x)}))}
function openList(){$("liveListPanel")?.classList.remove("hidden");h()}
function closeList(){$("liveListPanel")?.classList.add("hidden")}
function offline(x){const p=$("liveOfflineInfo");if(!p)return;p.innerHTML='<div class="live-offline-card"><button class="live-panel-close" type="button">×</button><div class="live-offline-avatar">'+esc(x.avatar)+'</div><strong>'+esc(x.name)+'</strong><span>⚫ OFFLINE</span><small>'+esc(x.game||x.category||"Стример")+'</small><p>'+(x.lastStreamAt?"Последний эфир: "+fmt(x.lastStreamAt):"Информация о последнем эфире пока отсутствует.")+'</p>'+(x.lastStreamTitle?"<p>"+esc(x.lastStreamTitle)+"</p>":"")+'</div>';p.classList.remove("hidden");p.querySelector(".live-panel-close")?.addEventListener("click",()=>p.classList.add("hidden"))}
function select(id,user){const x=S.all.find(v=>v.id===id);if(!x||!x.live||!x.selectedSource)return;S.selectedId=x.id;S.muted=true;main(x);carousel();if(user)h()}
function random(){const x=shuffle(S.online)[0]||null;S.selectedId=x?.id||null;S.muted=true;main(x);carousel()}
function refresh(payload){S.all=normalize(payload);S.online=S.all.filter(x=>x.live&&x.selectedSource);const x=S.all.find(v=>v.id===S.selectedId);if(!x||!x.live||!x.selectedSource)random();else{S.muted=true;main(x);carousel()}list()}
async function poll(){if(!cfg.endpoint||S.loading)return;S.loading=true;try{const r=await fetch(cfg.endpoint,{cache:"no-store",credentials:"omit"});if(!r.ok)throw Error("LIVE endpoint "+r.status);refresh(await r.json())}catch(e){console.warn("FREEzzzGames LIVE monitor unavailable:",e);if(!S.all.length)refresh([])}finally{S.loading=false}}
function visibility(){const screen=window.FZG?.state?.get?.().screen||"home";const home=screen==="home";$("liveView")?.classList.toggle("hidden",!home);document.getElementById("mainPortal")?.classList.toggle("live-home-mode",home);if(!home)closeList()}
function init(){if(!$("liveView"))return;$("liveListBtn")?.addEventListener("click",openList);$("liveListClose")?.addEventListener("click",closeList);$("liveListPanel")?.addEventListener("click",e=>{if(e.target.id==="liveListPanel")closeList()});window.FZG?.state?.subscribe?.(visibility);visibility();refresh([]);poll();setInterval(poll,Math.max(15000,Number(cfg.pollMs)||30000))}
window.FZG=window.FZG||{};window.FZG.live={refresh,poll,select,getState:()=>({...S}),onSoundChange:null};init();
})();