const GAME_CARDS = [
  {id:"deepsea",title:"The Deep Sea",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Исследуй глубины океана."},
  {id:"spacetrekk",title:"SpaceTrekk",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Интерактивный 3D-исследователь Солнечной системы с планетами и космическими объектами."},
  {id:"windowswap",title:"Window Swap",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Смотри на окна и виды из разных мест."},
  {id:"spaceelevator",title:"Space Elevator",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Поднимайся от поверхности Земли к космосу."},
  {id:"ancientearth",title:"Ancient Earth Globe",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Исследуй Землю в разные геологические эпохи."},
  {id:"radiogarden",title:"Radio Garden",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Исследуй радиостанции по всему миру."},
  {id:"geoguessr",title:"GeoGuessr",genre:"ИНТЕРАКТИВНЫЙ МИР",desc:"Определяй места по панорамам и географии."},
  {id:"patatap",title:"Patatap",genre:"ТВОРЧЕСТВО",desc:"Создавай звуки и анимации нажатием клавиш."},
  {id:"quickdraw",title:"Quick, Draw!",genre:"ТВОРЧЕСТВО",desc:"Рисуй объекты, а нейросеть Google попробует угадать их."},
  {id:"brunosimon",title:"Bruno Simon Portfolio",genre:"ТВОРЧЕСТВО",desc:"Интерактивное 3D-портфолио."},
  {id:"pollock",title:"Jackson Pollock Art",genre:"ТВОРЧЕСТВО",desc:"Интерактивный проект о живописи Jackson Pollock."},
  {id:"typatone",title:"Typatone",genre:"ТВОРЧЕСТВО",desc:"Превращай текст в музыку."},
  {id:"plink",title:"Plink",genre:"ТВОРЧЕСТВО",desc:"Интерактивный музыкальный эксперимент."},
  {id:"linerider",title:"Line Rider",genre:"ТВОРЧЕСТВО",desc:"Рисуй трассы и наблюдай за движением персонажа."},
  {id:"2048",title:"2048",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Соединяй одинаковые плитки."},
  {id:"password",title:"The Password Game",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Создай пароль, выполняющий всё больше правил."},
  {id:"remojibus",title:"Remojibus",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Разгадывай ребусы из эмодзи."},
  {id:"fillsquare",title:"Fill the Square",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Заполняй поле и решай пространственные задачи."},
  {id:"ricochetdaily",title:"Ricochet Daily",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Рассчитывай отскоки и проходи ежедневную задачу."},
  {id:"evolutiontrust",title:"The Evolution of Trust",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Интерактивное исследование доверия и стратегии."},
  {id:"littlealchemy2",title:"Little Alchemy 2",genre:"ПАЗЛЫ И ЛОГИКА",desc:"Соединяй элементы и открывай новые."},
  {id:"snake",title:"Snake",genre:"АРКАДЫ И КЛАССИКА",desc:"Классическая змейка."},
  {id:"doodlejump",title:"Doodle Jump",genre:"АРКАДЫ И КЛАССИКА",desc:"Прыгай всё выше по платформам."},
  {id:"puffpilot",title:"Puff Pilot",genre:"АРКАДЫ И КЛАССИКА",desc:"Проводи воздушный поток через кольца."},
  {id:"pokeclicker",title:"PokéClicker",genre:"АРКАДЫ И КЛАССИКА",desc:"Кликер с коллекционированием существ."},
  {id:"candybox2",title:"Candy Box 2",genre:"АРКАДЫ И КЛАССИКА",desc:"Накопление конфет превращается в приключение."},
  {id:"dino",title:"Dino T-Rex Game",genre:"АРКАДЫ И КЛАССИКА",desc:"Мини-игра с бегущим динозавром."},
  {id:"pip",title:"PIP: Skull Demo",genre:"АРКАДЫ И КЛАССИКА",desc:"Небольшой браузерный игровой прототип."},
  {id:"townscaper",title:"Townscaper",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Строй маленькие города без заданного сценария."},
  {id:"infinitecraft",title:"Infinite Craft",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Комбинируй элементы и открывай новые."},
  {id:"addtown",title:"Add Town ≈ 2048!",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Объединяй плитки и развивай город."},
  {id:"gridland",title:"Gridland",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Соединяй ресурсы и развивай поселение."},
  {id:"bouncyballs",title:"Bouncy Balls",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Интерактивные прыгающие шарики."},
  {id:"alchemy2",title:"Alchemy 2",genre:"СИМУЛЯТОРЫ И ПЕСКОЧНИЦЫ",desc:"Комбинируй элементы и создавай новые."},
  {id:"protocol",title:"Protocol ERRORMIND",genre:"ЭКСПЕРИМЕНТАЛЬНЫЕ ПРОЕКТЫ",desc:"Браузерная серия логических уровней."},
  {id:"lumenoffice",title:"Lumen Office RPG",genre:"ЭКСПЕРИМЕНТАЛЬНЫЕ ПРОЕКТЫ",desc:"Исследуй офис и решай загадки."},
  {id:"typehelp",title:"Type Help",genre:"ПАЗЛ • ДЕТЕКТИВ",desc:"Текстовый детектив: исследуй файлы старого компьютера и собирай улики."},
  {id:"alchemize",title:"Alchemize",genre:"СТРАТЕГИЯ",desc:"Стратегическая настольная игра: размещай зелья, создавай самоцветы и играй против ИИ."},
  {id:"uselessweb",title:"The Useless Web",genre:"ИНТЕРНЕТ-ЭКСПЕРИМЕНТ",desc:"Один клик — и ты попадаешь на случайный необычный сайт."},
  {id:"pacman",title:"PAC-MAN",genre:"АРКАДЫ • КЛАССИКА",desc:"Классическая аркада: собирай точки в лабиринте и избегай призраков."},
  {id:"coptercave",title:"Copter Cave",genre:"АРКАДЫ • РЕАКЦИЯ",desc:"Управляй полётом одним касанием: удерживай, чтобы подниматься, и отпускай, чтобы снижаться."},
  {id:"helicopter",title:"Helicopter Game",genre:"АРКАДЫ • КЛАССИКА",desc:"Пролети как можно дальше через туннель, избегая препятствий."},
]; 

const CATEGORIES = [
  {id:"worlds",name:"ИНТЕРАКТИВНЫЕ МИРЫ",ids:["deepsea","spacetrekk","windowswap","spaceelevator","ancientearth","radiogarden","geoguessr"]},
  {id:"creative",name:"ТВОРЧЕСТВО • МУЗЫКА • АРТ",ids:["patatap","quickdraw","brunosimon","pollock","typatone","plink","linerider"]},
  {id:"puzzles",name:"ПАЗЛЫ • ЛОГИКА",ids:["2048","password","remojibus","fillsquare","ricochetdaily","evolutiontrust","littlealchemy2"]},
  {id:"arcade",name:"АРКАДЫ • КЛАССИКА",ids:["snake","doodlejump","puffpilot","pokeclicker","candybox2","dino","pip","pacman","coptercave","helicopter"]},
  {id:"sandbox",name:"СИМУЛЯТОРЫ • ПЕСКОЧНИЦЫ",ids:["townscaper","infinitecraft","addtown","gridland","bouncyballs","alchemy2"]},
  {id:"experimental",name:"ЭКСПЕРИМЕНТАЛЬНЫЕ ПРОЕКТЫ",ids:["protocol","lumenoffice","typehelp","alchemize","uselessweb"]},
]; 

const GAME_LINKS = {
  "deepsea":"https://neal.fun/deep-sea/",
  "spacetrekk":"https://www.spacetrekk.com/",
  "windowswap":"https://window-swap.com/",
  "spaceelevator":"https://neal.fun/space-elevator/",
  "ancientearth":"https://dinosaurpictures.org/ancient-earth/",
  "radiogarden":"https://radio.garden/",
  "geoguessr":"https://www.geoguessr.com/",
  "patatap":"https://patatap.com/",
  "quickdraw":"https://quickdraw.withgoogle.com/",
  "brunosimon":"https://bruno-simon.com/",
  "pollock":"https://www.moma.org/interactives/exhibitions/1998/pollock/website100/txt_intro.html",
  "typatone":"https://typatone.com/",
  "plink":"https://www.experiments.withgoogle.com/plink-multiplayer-music-experience",
  "linerider":"https://www.linerider.com/",
  "2048":"https://play2048.co/",
  "password":"https://neal.fun/password-game/",
  "remojibus":"https://starzonmyarmz.github.io/remojibus/",
  "fillsquare":"https://ryanbalieiro.github.io/fill-the-square/",
  "ricochetdaily":"https://teknamin.github.io/ricochet-daily/",
  "evolutiontrust":"https://ncase.me/trust/",
  "littlealchemy2":"https://littlealchemy2.com/",
  "snake":"https://www.snake.at/game/1.3/index.html",
  "doodlejump":"https://cozyrain.github.io/DoodleJumpGame/",
  "puffpilot":"https://bte808.github.io/fun-20260601-a-puff-pilot/",
  "pokeclicker":"https://www.pokeclicker.com/",
  "candybox2":"https://candybox2.github.io/",
  "dino":"https://chromedino.com/embed/",
  "pip":"https://bandinopla.github.io/pip-skull-demo/",
  "townscaper":"https://www.townscapergame.com/",
  "infinitecraft":"https://neal.fun/infinite-craft/",
  "addtown":"https://www.lexaloffle.com/bbs/?pid=add_town",
  "gridland":"https://gridland.doublespeakgames.com/",
  "bouncyballs":"https://bouncyballs.org/",
  "alchemy2":"https://littlealchemy2.com/",
  "protocol":"https://protocol-errormind.github.io/",
  "alchemize":"https://brusi.itch.io/alchemize",
  "uselessweb":"https://theuselessweb.com/",
  "lumenoffice":"https://samirsaad786.github.io/LumenOfficeRPG/",
  "typehelp":"https://william-rous.itch.io/type-help",
  "pacman":"https://doodles.google/doodle/30th-anniversary-of-pac-man/",
  "coptercave":"https://arcade.now/copter-cave/",
  "helicopter":"https://www.gamesloth.com/arcade/helicopter/",
};

export { GAME_CARDS, CATEGORIES, GAME_LINKS };
